passport-api-test:
  login: http://localhost:8000/api/login
  register: http://localhost:8000/api/user
  update_user: http://localhost:8000/api/user
  users: http://localhost:8000/api/user
  details: http://localhost:8000/api/details
  create_rol: http://localhost:8000/api/rol
  update_rol: http://localhost:8000/api/update_rol
  assign_rol: http://localhost:8000/api/assign_rol
  change_password: http://localhost:8000/api/change_password
  auth_workflow_action: http://localhost:8000/api/auth_workflow_action
  user_workflow_actions: http://localhost:8000/api/user_workflow_actions
  emails: http://localhost:8000/api/emails

passport-api:
  login: http://passport-api-dev.us-west-2.elasticbeanstalk.com/api/login
  register: http://passport-api-dev.us-west-2.elasticbeanstalk.com/api/user
  update_user: http://passport-api-dev.us-west-2.elasticbeanstalk.comm/api/user
  users: http://passport-api-dev.us-west-2.elasticbeanstalk.com/api/user
  details: http://passport-api-dev.us-west-2.elasticbeanstalk.com/api/details
  create_rol: http://passport-api-dev.us-west-2.elasticbeanstalk.com/api/rol
  update_rol: http://passport-api-dev.us-west-2.elasticbeanstalk.com/api/update_rol
  assign_rol: http://passport-api-dev.us-west-2.elasticbeanstalk.com/api/assign_rol
  change_password: http://passport-api-dev.us-west-2.elasticbeanstalk.com/api/change_password
  auth_workflow_action: http://passport-api-dev.us-west-2.elasticbeanstalk.com/api/auth_workflow_action
  user_workflow_actions: http://passport-api-dev.us-west-2.elasticbeanstalk.com/api/user_workflow_actions
  emails: http://passport-api-dev.us-west-2.elasticbeanstalk.com/api/emails