dummy_workflow:
  a: ['rol1', 'rol2', 'rol3']
  b: ['rol4', 'ro6', 'rol7']
  c: ['rol4', 'ro6', 'rol7', 'worker1', 'worker2', 'Professor']

denuncia_mp:
  nueva: ['fiscal_mrd']
  pendiente_evaluar: ['fiscal_mrd']
  delitos_asignados: ['fiscal_mrd']
  auto_elaborado: ['fiscal_mrd']
  fiscales_asignados: ['fiscal_coordinador_mrd']
  entregada_a_fiscalia_correspondiente: ['fiscal_mrd']
  pendiente_autorizacion_auto_cierre_administrativo: ['fiscal_coordinador_mrd']
  pendiente_recibir_notificacion_auto_cierre_firmada: ['secretaria_fiscal_mrd']
  pendiente_recibir_notificacion_de_conformidad_auto_cierre: ['secretaria_fiscal_mrd']
  auto_cierre_aceptado: ['secretaria_fiscal_mrd']
  pendiente_aceptacion_apelacion_auto_cierre: ['dgf']
  apelacion_aceptada: ['secretaria_fiscal_mrd']
  entregada_a_maadeh: ['secretaria_fiscal_mrd']

denuncia_ss:
  nueva: ['receptor_denuncia_ss']
  pendiente_revision: ['fiscal_asignado_ss']
  delitos_tipificados: ['fiscal_asignado_ss']
  aceptada: ['receptor_denuncia_ss']
  no_aceptada: ['receptor_denuncia_ss']
  descripcion_hechos_firmados: ['receptor_denuncia_ss']
  remitida_ministerio_publico: ['receptor_denuncia_ss']

recepcion_documento:
  nuevo: ['receptor_documentos']
  recibido: ['receptor_documentos']
  dependencia_asignada: ['receptor_documentos']
  remitido: ['receptor_documentos']
