dummy_workflow:
  t1: ['rol1', 'rol2', 'rol3']
  t2: ['worker1', 'worker2', 'Professor']
  t3: ['rol4', 'rol6', 'rol7']

denuncia_mp:
  remitir_a_evaluacion: ['MRD']
  asignar_delitos: ['fiscal_mrd']
  elaborar_auto: ['fiscal_mrd']
  asignar_fiscales: ['fiscal_mrd']
  entregar_expediente_fiscalia: ['fiscal_coordinador_mrd']
  aplicar_auto_cierre: ['fiscal_mrd']
  autorizar_auto_cierre: ['fiscal_coordinador_mrd']
  solicitar_conformidad_auto_cierre: ['secretaria_fiscal_mrd']
  aceptar_auto_cierre: ['secretaria_fiscal_mrd']
  apelar_auto_cierre: ['secretaria_fiscal_mrd']
  aceptar_apelacion_auto_cierre: ['dgf']
  entregar_a_maadeh: ['secretaria_fiscal_mrd']

denuncia_ss:
  recibir_denuncia: ['receptor_denuncia_ss']
  tipificar_delitos: ['fiscal_asignado_ss']
  aceptar_denuncia: ['fiscal_asignado_ss']
  desestimar: ['fiscal_asignado_ss']
  firmar_descripcion_hechos: ['receptor_denuncia_ss']
  remitir_ministerio_publico: ['receptor_denuncia_ss']

recepcion_documento:
  recibir_documento: ['receptor_documentos']
  asignar_dependencia: ['receptor_documentos']
  remitir: ['receptor_documentos']

acuerdo_interno_ss:
  elaborar_acto: ['depto_rrhh']
  redactar_acuerdo: ['depto_rrhh']
  firmar_acuerdo: ['depto_rrhh']
  entregar_notificacion: ['depto_rrhh']
  actualizar_bd: ['depto_rrhh']

extraer_dato_sistema_ss:
  recepcionar_acuerdo: ['secretario_general']
  bajar_persona: ['secretario_general']
  generar_respuesta: ['secretario_general']
  enviar_archivo: ['secretario_general']

delito_contra_propiedad_ss:
  asignar_denuncia: ['depto_delito_contra_propiedad']
  recibir_solicitud_nota_informacion: ['depto_delito_contra_propiedad']
  generar_informe_propuesta: ['depto_delito_contra_propiedad']
  remitir_informe_ss_fna: ['depto_delito_contra_propiedad']
  recibir_solicitud_peritaje_vehiculo: ['depto_delito_contra_propiedad']
  registrar_informacion_vehiculo: ['depto_delito_contra_propiedad']
  generar_acta_inspeccion: ['depto_delito_contra_propiedad']
  remitir_informe_ss_medicinaforensemp_fiscalmp: ['depto_delito_contra_propiedad']
  recibir_solicitud_diligencia: ['depto_delito_contra_propiedad']
  asignar_diligencia: ['depto_delito_contra_propiedad']
  generar_informes_diligencias: ['depto_delito_contra_propiedad']
  remitir_informe_ss_fiscalmp: ['depto_delito_contra_propiedad']
  recibir_solicitud_datos_estadisticos: ['depto_delito_contra_propiedad']
  registrar_actividades_mensuales: ['depto_delito_contra_propiedad']
  generar_informe_periodico_casos: ['depto_delito_contra_propiedad']
  remitir_informe_ss_estadisticaplaneacion: ['depto_delito_contra_propiedad']

informe_logistico_ss:
  verificar_existencias: ['depto_logistica']
  generar_informe_respuesta: ['depto_logistica']
  enviar_respuesta: ['depto_logistica']
  generar_informe_respectivo: ['depto_logistica']
  generar_informe_solicitud: ['depto_logistica']
  enviar_solicitud: ['depto_logistica']
  generar_informe_avisos: ['depto_logistica']

nueva_promocion_ss:
  obtener_listados: ['jefe_rrhh']
  solicitar_informacion: ['jefe_rrhh']
  recibir_informacion: ['jefe_rrhh']
  extender_estructura_presupuestaria: ['jefe_rrhh']

contestacion_oficio_ss:
  ingresar_solicitud: ['jefe_departamentos']
  procesar_informacion: ['jefe_departamentos']
  autorizar_contestacion: ['jefe_departamentos']
  enviar_autorizacion_jefe: ['jefe_departamentos']

informe_perfilacion_criminal_ss:
  revisar_expediente: ['jefe_departamentos']
  analizar_expediente: ['jefe_departamentos']
  individualizar: ['jefe_departamentos']
  generar_perfil_victima: ['jefe_departamentos']
  generar_perfil_sospechoso: ['jefe_departamentos']
  generar_matriz_vinculacion_victima: ['jefe_departamentos']
  generar_matriz_vinculacion_sospechoso: ['jefe_departamentos']
  nueva_solicitud_matriz_vinculacion: ['jefe_departamentos']
  vincular: ['jefe_departamentos']
  realizar_estudios: ['jefe_departamentos']
  generar_antecedentes_victima: ['jefe_departamentos']
  generar_antecedentes_sospechoso: ['jefe_departamentos']
  generar_informe_final_victima: ['jefe_departamentos']
  generar_informe_final_sospechoso: ['jefe_departamentos']
  informe_final_entregado: ['jefe_departamentos']

informe_disciplinario_ss:
  procesar_informacion: ['jefe_rrhh']
  realizar_audiencia_descargo: ['jefe_rrhh']
  generar_dictamen: ['secretaria_ejecutiva']
  generar_informe_resolucion: ['secretaria_ejecutiva']
  notificar_resolucion: ['secretaria_ejecutiva']
  archivar_resolucion: ['secretaria_ejecutiva']
  remitir_resolucion_direccion_general: ['secretaria_ejecutiva']
  ejecutar_sancion: ['secretaria_ejecutiva']
  archivar_informe_final: ['jefe_rrhh']

informe_delito_contra_vida_ss:
  realizar_lavantamiento_cadaverico: ['investigador_delitos_contra_vida']
  buscar_testigos: ['investigador_delitos_contra_vida']
  tomar_declaracion_testigos: ['investigador_delitos_contra_vida']
  recolectar_informacion_hecho_testigos: ['investigador_delitos_contra_vida']
  recolectar_informacion_hecho: ['investigador_delitos_contra_vida']
  realizar_primeras_diligencias: ['investigador_delitos_contra_vida']
  generar_informe_preliminar: ['investigador_delitos_contra_vida']
  remitir_informe_preliminar: ['investigador_delitos_contra_vida']
  finalizar_informe_preliminar: ['investigador_delitos_contra_vida']
  recibir_auto_ampliacion_avances: ['investigador_delitos_contra_vida']
  realizar_diligencias_complementarias_avances: ['investigador_delitos_contra_vida']
  incorporar_resultados_periciales_avances: ['investigador_delitos_contra_vida']
  generar_informe_avances: ['investigador_delitos_contra_vida']
  remitir_informe_avances: ['investigador_delitos_contra_vida']
  finalizar_informe_avances: ['investigador_delitos_contra_vida']
  recibir_auto_ampliacion_final: ['investigador_delitos_contra_vida']
  realizar_diligencias_complementarias_final: ['investigador_delitos_contra_vida']
  incorporar_resultados_periciales_final: ['investigador_delitos_contra_vida']
  generar_informe_final: ['investigador_delitos_contra_vida']
  remitir_informe_final: ['investigador_delitos_contra_vida']
  finalizar_informe_final: ['investigador_delitos_contra_vida']
  recibir_orden_captura: ['investigador_delitos_contra_vida']
  orden_ejecutada: ['investigador_delitos_contra_vida']
  remitir_sospechoso: ['investigador_delitos_contra_vida']
  realizar_primeras_diligencias_testigos_flagrancia: ['investigador_delitos_contra_vida']
  realizar_primeras_diligencias_flagrancia: ['investigador_delitos_contra_vida']
  realizar_diligencias_complentarias_flagrancia: ['investigador_delitos_contra_vida']
  generar_informe_remision: ['investigador_delitos_contra_vida']
  remitir_informe_remision: ['investigador_delitos_contra_vida']
  generar_informe_final_flagrancia: ['investigador_delitos_contra_vida']
  remitir_informe_final_flagrancia: ['investigador_delitos_contra_vida']
  finalizar_informe_final_flagrancia: ['investigador_delitos_contra_vida']

estandarizacion_ss:
  generar_manual_nuevo: ['unidad_supervicion_coordinacion']
  generar_actualizacion_instructivo: ['unidad_supervicion_coordinacion']
  generar_nuevo_boletin: ['unidad_supervicion_coordinacion']
  presentar_manual: ['unidad_supervicion_coordinacion']
  presentar_necesidades: ['unidad_supervicion_coordinacion']
  seleccionar_tema: ['unidad_supervicion_coordinacion']
  aprobar_manual: ['unidad_supervicion_coordinacion']
  realizar_cronograma: ['unidad_supervicion_coordinacion']
  elaborar_boletin: ['unidad_supervicion_coordinacion']
  difundir_manual: ['unidad_supervicion_coordinacion']
  actualizar_documento: ['unidad_supervicion_coordinacion']
  revisar_boletin: ['unidad_supervicion_coordinacion']
  presentar_instructivo: ['unidad_supervicion_coordinacion']
  presentar_boletin: ['unidad_supervicion_coordinacion']
  difundir_manual: ['unidad_supervicion_coordinacion']
  aprobar_instructivo: ['unidad_supervicion_coordinacion']
  aprobar_boletin: ['unidad_supervicion_coordinacion']
  socializar_instructivo: ['unidad_supervicion_coordinacion']
  difundir_boletin: ['unidad_supervicion_coordinacion']
  socializar_manual: ['unidad_supervicion_coordinacion']
  difundir_manual: ['unidad_supervicion_coordinacion']

informe_escena_delito_ss:
  procesar_escena_delito: ['policia_tecnico']
  procesar_indicios: ['policia_tecnico']
  procesar_pertenencias: ['policia_tecnico']
  procesar_allanamiento: ['policia_tecnico']
  procesar_exhumacion: ['policia_tecnico']
  reconstruir_hechos: ['policia_tecnico']
  realizar_pruebas_luminol: ['policia_tecnico']
  enviar_indicios_laboratorio: ['policia_tecnico']
  enviar_pertenencias_mp: ['policia_tecnico']
  recibir_resulatados_laboratorio: ['policia_tecnico']
  generar_informe_pericial_laboratorios: ['policia_tecnico']
  generar_informe_pericial_pertenencias: ['policia_tecnico']
  generar_informe_pericial_allanamiento: ['policia_tecnico']
  generar_informe_pericial_exhumacion: ['policia_tecnico']
  generar_informe_pericial_hechos: ['policia_tecnico']
  generar_informe_pericial_luminol: ['policia_tecnico']
  generar_movil: ['policia_tecnico']
  generar_informe_final: ['policia_tecnico']
  remitir_informe_final_mp: ['policia_tecnico']
  recibir_nueva_orden_captura: ['policia_tecnico']
  ejecutar_orden_captura: ['policia_tecnico']
  remitir_sospechoso_pj: ['policia_tecnico']

informe_topografia_forense_ss:
  verificar_equipos: ['depto_topografia_forense']
  determinar_levantamiento: ['depto_topografia_forense']
  realizar_levantamiento_topografico: ['depto_topografia_forense']
  verificar_viabilidad_equipos: ['depto_topografia_forense']
  verificar_viabilidad_hechos: ['depto_topografia_forense']
  verificar_viabilidad_bosquejo: ['depto_topografia_forense']
  realizar_levantamiento_topografico: ['depto_topografia_forense']
  realizar_exhumacion: ['depto_topografia_forense']
  reconstruir_hechos: ['depto_topografia_forense']
  generar_informe_final_hechos: ['depto_topografia_forense']
  generar_informe_final_exhumacion: ['depto_topografia_forense']
  generar_informe_final_levantamiento: ['depto_topografia_forense']
  remitir_informe_final_mp: ['depto_topografia_forense']

denuncia_proceso_general_ss:
  nueva_denuncia: ['receptor_denuncia_ss']
  registro_denuncia_infraganti: ['receptor_denuncia_ss']
  verifico_identidad_detenido: ['receptor_denuncia_ss']
  verifico_identidad_denunciante: ['receptor_denuncia_ss']
  remite_solicitud_defensor_defensa_publica_pj: ['receptor_denuncia_ss']
  tipifico_delito: ['receptor_denuncia_ss']
  remitido_defensa_publica: ['receptor_denuncia_ss']
  autorizo_delito: ['receptor_denuncia_ss']
  transcribio_denuncia: ['receptor_denuncia_ss']
  notifico_denunciante_denuncia_no_aceptada: ['receptor_denuncia_ss']
  genero_reporte_denuncia_firmado: ['receptor_denuncia_ss']
  entrego_notificacion_denunciante: ['receptor_denuncia_ss']
  remitio_donde_corresponde: ['receptor_denuncia_ss']
  verifico_denuncias_similares: ['receptor_denuncia_ss']
  agrupo_denuncias_similares: ['receptor_denuncia_ss']
  imprimio_denuncia_individual: ['receptor_denuncia_ss']
  remitio_denuncia_mrd_mp: ['receptor_denuncia_ss']
  recibio_requerimiento_investigativo: ['receptor_denuncia_ss']
  asigno_investigador_especializado: ['jefe_denuncias']
  genero_informe_avances: ['investigador_depto_especializado']
  realizo_informe_flagrancia_resultados: ['investigador_urid']
  remite_informe_investigador_fiscal_instruccion_mp: ['investigador_urid']
  remitio_informe_avances_fiscal_instruccion_mp: ['investigador_depto_especializado']
  informe_investigador_remitido: ['investigador_urid']
  genero_informe_preliminar: ['investigador_depto_especializado']
  remitio_informe_preliminar_fiscal_instruccion_mp: ['investigador_depto_especializado']
  genero_informe_especializado_final: ['investigador_depto_especializado']
  remitio_informe_especializado_final_mp: ['investigador_depto_especializado']
  recibio_nueva_orden_captura_juez_pj: ['investigador_depto_especializado']
  ejecuto_orden: ['investigador_depto_especializado']
  remitio_detenido_juez_pj: ['investigador_depto_especializado']
  orden_ejecutada: ['investigador_depto_especializado']

informe_cuadro_estadistico_ss:
  recepcionar_informacion: ['jefe_unidad_informacion_estadistica']
  ingresar_informacion_recibida: ['jefe_unidad_informacion_estadistica']
  consolidar_informacion: ['jefe_unidad_informacion_estadistica']
  consultar_bd: ['jefe_unidad_informacion_estadistica']
  obtener_resultados: ['jefe_unidad_informacion_estadistica']
  elaborar_cuadros_informe: ['jefe_unidad_informacion_estadistica']
  enviar_informe: ['jefe_unidad_informacion_estadistica']

solicitud_revelado_fotografia_ss:
  realizar_fotografias: ['depto_fotografias']
  almacenar_fotografias: ['depto_fotografias']
  abastecer_fotografias: ['depto_fotografias']
  clasificar_depurar_fotografias: ['depto_fotografias']
  revelar_fotografias: ['depto_fotografias']
  registrar_fotografias_fisicas: ['depto_fotografias']
  elaborar_album: ['depto_fotografias']
  entregar_album: ['depto_fotografias']

solicitud_revisar_informacion_digital_ss:
  verificar_datos: ['jefe_inmediato']
  confirmar_datos: ['jefe_inmediato']
  corregir_datos: ['jefe_inmediato']
  reportar_personal_duplicado_correctos:  ['jefe_inmediato']
  reportar_personal_duplicado_corregidos: ['jefe_inmediato']
  depurar_lista: ['jefe_inmediato']
  elaborar_reporte: ['jefe_inmediato']
  entregar_reporte: ['jefe_inmediato']

solicitud_estructura_criminal_ss:
  verificar_registro_ordeno_solicitud: ['depto_analisis_estretegico']
  recepcionar_informacion: ['depto_analisis_estretegico']
  clasificar_informacion: ['depto_analisis_estretegico']
  buscar_informacion: ['depto_analisis_estretegico']
  informacion_verificada: ['depto_analisis_estretegico']
  generar_expediente: ['depto_analisis_estretegico']
  entregar_solicitud: ['depto_analisis_estretegico']

solicitud_record_historial:
  verificar_requisitos: ['depto_infracciones']
  recepcionar_esquelas_identidades: ['depto_infracciones']
  avisar_requisitos: ['depto_infracciones']
  elaborar_respuesta: ['depto_infracciones']
  respuesta_generada: ['depto_infracciones']
  recibir_documentacion: ['depto_infracciones']
  elaborar_constancia: ['depto_infracciones']
  elaborada_constancia: ['depto_infracciones']
  redactar_solicitud_ciudadano: ['depto_infracciones']
  enviar_solicitud: ['depto_infracciones']
  enviado_solicitud: ['depto_infracciones']

solicitud_transporte_almacen_general_ss:
  recepcionar_indicios: ['jefe_transito_evidencias']
  verificar_requisitos: ['jefe_transito_evidencias']
  asignar_numero_oficio: ['jefe_transito_evidencias']
  transportar_indicios: ['jefe_transito_evidencias']

solicitud_antecedente_ss:
  recibir_solicitud_ciudadano: ['depto_antecedentes']
  recibir_solicitud_juez_fiscal: ['depto_antecedentes']
  recibir_solicitud_depto_detenidos: ['depto_antecedentes']
  registrar_solicitud: ['depto_antecedentes']
  verificar_solicitud: ['depto_antecedentes']
  identificar_persona: ['depto_antecedentes']
  verificar_antecedentes: ['depto_antecedentes']
  registrar_solicitud: ['depto_antecedentes']
  elaborar_ficha: ['depto_antecedentes']
  archivar_documento_identifico: ['depto_antecedentes']
  archivar_documento_ficha: ['depto_antecedentes']
  registrar_record_solicitud: ['depto_antecedentes']
  registrar_record_antecedentes: ['depto_antecedentes']
  enviar_orden_captura: ['depto_antecedentes']
  emitir_record: ['depto_antecedentes']
  entregar_record: ['depto_antecedentes']
  entregado_antecedente: ['depto_antecedentes']
  archviado_documento: ['depto_antecedentes']

informe_urid_ss:
  nuevo_requerimiento_investigativo_fiscal: ['investigador_urid']
  toma_declaraciones: ['investigador_urid']
  nuevo_informe_pericial: ['investigador_urid']
  envio_indicios_laboratorio: ['investigador_urid']
  recepcion_resultados_laboratorio: ['investigador_urid']
  actualizo_informe_pericial: ['investigador_urid']
  registro_perfil_sospechoso: ['investigador_urid']
  genero_informe_investigativo: ['investigador_urid']
  ejecuto_orden_judicial: ['investigador_urid']
  genero_informe_final: ['investigador_urid']
  envia_informe_final_fiscal_instruccion_mp: ['investigador_urid']
  informe_final_remitido_mp: ['investigador_urid']
