dummy_workflow:
  a: ['rol1', 'rol2', 'rol3']
  b: ['rol4', 'ro6', 'rol7']
  c: ['rol4', 'ro6', 'rol7', 'worker1', 'worker2', 'Professor']

denuncia_mp:
  nueva: ['fiscal_mrd']
  pendiente_evaluar: ['fiscal_mrd']
  delitos_asignados: ['fiscal_mrd']
  auto_elaborado: ['fiscal_mrd']
  fiscales_asignados: ['fiscal_coordinador_mrd']
  entregada_a_fiscalia_correspondiente: ['fiscal_mrd']
  pendiente_autorizacion_auto_cierre_administrativo: ['fiscal_coordinador_mrd']
  pendiente_recibir_notificacion_auto_cierre_firmada: ['secretaria_fiscal_mrd']
  pendiente_recibir_notificacion_de_conformidad_auto_cierre: ['secretaria_fiscal_mrd']
  auto_cierre_aceptado: ['secretaria_fiscal_mrd']
  pendiente_aceptacion_apelacion_auto_cierre: ['dgf']
  apelacion_aceptada: ['secretaria_fiscal_mrd']
  entregada_a_maadeh: ['secretaria_fiscal_mrd']

denuncia_ss:
  nueva: ['receptor_denuncia_ss']
  pendiente_revision: ['fiscal_asignado_ss']
  delitos_tipificados: ['fiscal_asignado_ss']
  aceptada: ['receptor_denuncia_ss']
  no_aceptada: ['receptor_denuncia_ss']
  descripcion_hechos_firmados: ['receptor_denuncia_ss']
  remitida_ministerio_publico: ['receptor_denuncia_ss']

recepcion_documento:
  nuevo: ['receptor_documentos']
  recibido: ['receptor_documentos']
  dependencia_asignada: ['receptor_documentos']
  remitido: ['receptor_documentos']

acuerdo_interno_ss:
  nuevo_solicitud_acuerdo: ['depto_rrhh']
  elaboro_acto_solicitado: ['depto_rrhh']
  redacto_acuerdo: ['depto_rrhh']
  firmo_acuerdo: ['depto_rrhh']
  entrego_notificacion: ['depto_rrhh']
  actualizo_bd: ['depto_rrhh']

extraer_dato_sistema_ss:
  nuevo_instruccion: ['secretario_general']
  recepciono_verifico_documentos: ['secretario_general']
  realizo_baja_persona: ['secretario_general']
  genero_respuesta: ['secretario_general']
  archivo: ['secretario_general']

delito_contra_propiedad_ss:
  nueva_denuncia: ['depto_delito_contra_propiedad']
  asigno_denuncia: ['depto_delito_contra_propiedad']
  nueva_solicitud_nota_informacion: ['depto_delito_contra_propiedad']
  genero_informe_propuesta: ['depto_delito_contra_propiedad']
  nueva_solicitud_peritaje_vehiculo: ['depto_delito_contra_propiedad']
  registro_informacion_vehiculo: ['depto_delito_contra_propiedad']
  genero_acta_inspeccion: ['depto_delito_contra_propiedad']
  nueva_solicitud_diligencia: ['depto_delito_contra_propiedad']
  asigno_diligencia: ['depto_delito_contra_propiedad']
  genero_informes_diligencias: ['depto_delito_contra_propiedad']
  nueva_solicitud_datos_estadisticos: ['depto_delito_contra_propiedad']
  registro_actividades_mensuales: ['depto_delito_contra_propiedad']
  genero_informe_periodico_casos: ['depto_delito_contra_propiedad']
  remitio_informe_ss_fna: ['depto_delito_contra_propiedad']
  remitio_informe_ss_medicinaforensemp_fiscalmp: ['depto_delito_contra_propiedad']
  remitio_informe_ss_fiscalmp: ['depto_delito_contra_propiedad']
  remitio_informe_ss_estadisticaplaneacion: ['depto_delito_contra_propiedad']

informe_logistico_ss:
  nueva_solicitud: ['depto_logistica']
  verifico_solicitado: ['depto_logistica']
  genero_informe_respuesta: ['depto_logistica']
  genero_informe_solicitud: ['depto_logistica']
  envio_solicitud: ['depto_logistica']
  envio_respuesta: ['depto_logistica']
  genero_informe_respectivos: ['depto_logistica']

nueva_promocion_ss:
  recibe_solicitud_oficial: ['jefe_rrhh']
  obtuvo_listados_copias_id: ['jefe_rrhh']
  solicito_informacion_secretario_general: ['jefe_rrhh']
  recibio_informacion_solicitada: ['jefe_rrhh']
  extiendio_estructura_presupuestaria: ['jefe_rrhh']

contestacion_oficio_ss:
  nueva_solicitud:  ['jefe_departamentos']
  ingreso_solicitud_libro: ['jefe_departamentos']
  proceso_informacion: ['jefe_departamentos']
  autorizo_jefe_inmediato: ['jefe_departamentos']
  envio_contestacion: ['jefe_departamentos']

informe_perfilacion_criminal_ss:
  nueva_denuncia: ['jefe_departamentos']
  reviso_expediente_carencias: ['jefe_departamentos']
  analizo_expediente_sugerencias: ['jefe_departamentos']
  individualizo_victima_sospechoso: ['jefe_departamentos']
  genero_perfil_victima: ['jefe_departamentos']
  genero_perfil_sospechoso: ['jefe_departamentos']
  nueva_solicitud_matriz_vinculacion: ['jefe_departamentos']
  genero_matriz_vinculacion: ['jefe_departamentos']
  vinculo: ['jefe_departamentos']
  realizo_estudios: ['jefe_departamentos']
  genero_antecedetes_victima: ['jefe_departamentos']
  genero_antecedetes_sospechoso: ['jefe_departamentos']
  genero_informe_final: ['jefe_departamentos']
  entrego_informe_final: ['jefe_departamentos']

informe_disciplinario_ss:
  recibio_informe_inicial: ['jefe_rrhh']
  proceso_informacion: ['jefe_rrhh']
  realizo_audiencia_descargo: ['jefe_rrhh']
  genero_dictamen: ['secretaria_ejecutiva']
  genero_informe_resolucion: ['secretaria_ejecutiva']
  notifico_resolucion: ['secretaria_ejecutiva']
  archivo_resolucion: ['secretaria_ejecutiva']
  ejecuto_sancion: ['secretaria_ejecutiva']
  remitio_resolucion_direccion_general: ['secretaria_ejecutiva']
  archivo_informe_final: ['jefe_rrhh']

informe_delito_contra_vida_ss:
  nueva_denuncia: ['investigador_delitos_contra_vida']
  realizo_levantamiento_cadaverico: ['investigador_delitos_contra_vida']
  busco_testigos: ['investigador_delitos_contra_vida']
  tomo_declaracion_testigos: ['investigador_delitos_contra_vida']
  recolecto_informacion_hecho: ['investigador_delitos_contra_vida']
  realizo_primeras_diligencias: ['investigador_delitos_contra_vida']
  genero_informe_preliminar: ['investigador_delitos_contra_vida']
  remitio_informe_preliminar_mp: ['investigador_delitos_contra_vida']
  recibio_auto_ampliacion: ['investigador_delitos_contra_vida']
  realizo_diligencias_complementarias: ['investigador_delitos_contra_vida']
  incorporo_resultados_periciales: ['investigador_delitos_contra_vida']
  genero_informe_avances: ['investigador_delitos_contra_vida']
  remitio_informe_avances_mp: ['investigador_delitos_contra_vida']
  genero_informe_final: ['investigador_delitos_contra_vida']
  remitio_informe_final_mp: ['investigador_delitos_contra_vida']
  genero_informe_remision_detenido: ['investigador_delitos_contra_vida']
  remitio_informe_remision_mp: ['investigador_delitos_contra_vida']
  nueva_orden_captura_pj: ['investigador_delitos_contra_vida']
  ejecuto_orden_captura: ['investigador_delitos_contra_vida']
  sospechoso_remitido_pj: ['investigador_delitos_contra_vida']
  informe_enviado: ['investigador_delitos_contra_vida']

estandarizacion_ss:
  nueva_solicitud: ['unidad_supervicion_coordinacion']
  nuevo_manual: ['unidad_supervicion_coordinacion']
  nueva_actualizacion_instructivo: ['unidad_supervicion_coordinacion']
  nuevo_boletin_doctrinal_juridico: ['unidad_supervicion_coordinacion']
  presento_manual: ['unidad_supervicion_coordinacion']
  necesidades_cambio: ['unidad_supervicion_coordinacion']
  selecciono_tema: ['unidad_supervicion_coordinacion']
  manual_aprobado: ['unidad_supervicion_coordinacion']
  realizo_cronograma: ['unidad_supervicion_coordinacion']
  elaboro_boletin: ['unidad_supervicion_coordinacion']
  difundio_manual: ['unidad_supervicion_coordinacion']
  actualizo_documento: ['unidad_supervicion_coordinacion']
  reviso_boletin: ['unidad_supervicion_coordinacion']
  presento_instructivo: ['unidad_supervicion_coordinacion']
  presento_boletin: ['unidad_supervicion_coordinacion']
  manual_difundido: ['unidad_supervicion_coordinacion']
  instructivo_aprobado: ['unidad_supervicion_coordinacion']
  aprobo_boletin: ['unidad_supervicion_coordinacion']
  socializado: ['unidad_supervicion_coordinacion']
  difundio_boletin: ['unidad_supervicion_coordinacion']
  manual_socializado: ['unidad_supervicion_coordinacion']
  manual_difundido: ['unidad_supervicion_coordinacion']

informe_escena_delito_ss:
  nueva_denuncia: ['policia_tecnico']
  proceso_escena_delito: ['policia_tecnico']
  proceso_indicios: ['policia_tecnico']
  proceso_pertenencias: ['policia_tecnico']
  proceso_allanamiento: ['policia_tecnico']
  proceso_exhumacion: ['policia_tecnico']
  reconstruyo_hechos: ['policia_tecnico']
  realizo_pruebas_luminol: ['policia_tecnico']
  envio_indicios_laboratorio: ['policia_tecnico']
  envio_pertenencias_mp: ['policia_tecnico']
  recibio_resultados_laboratorio: ['policia_tecnico']
  genero_informe_pericial: ['policia_tecnico']
  genero_movil: ['policia_tecnico']
  genero_informe_final: ['policia_tecnico']
  nueva_orden_captura_pj: ['policia_tecnico']
  remitio_informe_final_mp: ['policia_tecnico']
  ejecuto_orden_captura: ['policia_tecnico']
  sospechoso_remitido_pj: ['policia_tecnico']

informe_topografia_forense_ss:
  nueva_denuncia: ['depto_topografia_forense']
  verifico_equipos: ['depto_topografia_forense']
  determino_levantamiento_acorde_hechos: ['depto_topografia_forense']
  realizo_bosquejo_topografico: ['depto_topografia_forense']
  verifico_viabilidad: ['depto_topografia_forense']
  realizo_levantamiento_topografico: ['depto_topografia_forense']
  realizo_exhumacion: ['depto_topografia_forense']
  reconstruyo_hechos: ['depto_topografia_forense']
  genero_informe_final: ['depto_topografia_forense']
  remitio_informe_final_mp: ['depto_topografia_forense']

denuncia_proceso_general_ss:
  nueva_denuncia: ['receptor_denuncia_ss']
  registro_denuncia_infraganti: ['receptor_denuncia_ss']
  verifico_identidad_detenido: ['receptor_denuncia_ss']
  verifico_identidad_denunciante: ['receptor_denuncia_ss']
  remite_solicitud_defensor_defensa_publica_pj: ['receptor_denuncia_ss']
  tipifico_delito: ['receptor_denuncia_ss']
  remitido_defensa_publica: ['receptor_denuncia_ss']
  autorizo_delito: ['receptor_denuncia_ss']
  transcribio_denuncia: ['receptor_denuncia_ss']
  notifico_denunciante_denuncia_no_aceptada: ['receptor_denuncia_ss']
  genero_reporte_denuncia_firmado: ['receptor_denuncia_ss']
  entrego_notificacion_denunciante: ['receptor_denuncia_ss']
  remitio_donde_corresponde: ['receptor_denuncia_ss']
  verifico_denuncias_similares: ['receptor_denuncia_ss']
  agrupo_denuncias_similares: ['receptor_denuncia_ss']
  imprimio_denuncia_individual: ['receptor_denuncia_ss']
  remitio_denuncia_mrd_mp: ['receptor_denuncia_ss']
  recibio_requerimiento_investigativo: ['receptor_denuncia_ss']
  asigno_investigador_especializado: ['jefe_denuncias']
  genero_informe_avances: ['investigador_depto_especializado']
  realizo_informe_flagrancia_resultados: ['investigador_urid']
  remite_informe_investigador_fiscal_instruccion_mp: ['investigador_urid']
  remitio_informe_avances_fiscal_instruccion_mp: ['investigador_depto_especializado']
  informe_investigador_remitido: ['investigador_urid']
  genero_informe_preliminar: ['investigador_depto_especializado']
  remitio_informe_preliminar_fiscal_instruccion_mp: ['investigador_depto_especializado']
  genero_informe_especializado_final: ['investigador_depto_especializado']
  remitio_informe_especializado_final_mp: ['investigador_depto_especializado']
  recibio_nueva_orden_captura_juez_pj: ['investigador_depto_especializado']
  ejecuto_orden: ['investigador_depto_especializado']
  remitio_detenido_juez_pj: ['investigador_depto_especializado']
  orden_ejecutada: ['investigador_depto_especializado']

informe_cuadro_estadistico_ss:
  nueva_autorizacion_informe: ['jefe_unidad_informacion_estadistica']
  recepciono_informacion: ['jefe_unidad_informacion_estadistica']
  ingreso_informacion_recibida: ['jefe_unidad_informacion_estadistica']
  consolido_informacion: ['jefe_unidad_informacion_estadistica']
  consulto_bd: ['jefe_unidad_informacion_estadistica']
  obtuvo_resultados: ['jefe_unidad_informacion_estadistica']
  elaboro_cuadro_informe: ['jefe_unidad_informacion_estadistica']
  informe_enviado_operacion_direccion_subdireccion: ['jefe_unidad_informacion_estadistica']

solicitud_revelado_fotografia_ss:
  nueva_denuncia: ['depto_fotografias']
  realizo_fotografias: ['depto_fotografias']
  almaceno_fotografias_digital: ['depto_fotografias']
  abastecio_material: ['depto_fotografias']
  clasifico_depuro_fotografias: ['depto_fotografias']
  revelo_fotografias: ['depto_fotografias']
  registro_fotografias_fisicas: ['depto_fotografias']
  elaboro_album: ['depto_fotografias']
  album_entregado_policia_tecnico: ['depto_fotografias']

solicitud_revisar_informacion_digital_ss:
  nueva_solicitud: ['jefe_inmediato']
  verifico_datos_bd: ['jefe_inmediato']
  confirmo_datos_correctos: ['jefe_inmediato']
  corrigio_datos: ['jefe_inmediato']
  reporto_personal_duplicado: ['jefe_inmediato']
  filtro_lista_depurada: ['jefe_inmediato']
  elaboro_reporte_correspondeinte: ['jefe_inmediato']
  entrego_reporte_director_general: ['jefe_inmediato']

solicitud_estructura_criminal_ss:
  nueva_solicitud: ['depto_analisis_estretegico']
  verifico_registro_ordeno_solicitud: ['depto_analisis_estretegico']
  recepciono_informacion_investigada: ['depto_analisis_estretegico']
  clasifico_informacion_bd: ['depto_analisis_estretegico']
  busco_informacion_sistema: ['depto_analisis_estretegico']
  ingreso_informacion_verificada_bd: ['depto_analisis_estretegico']
  genero_expediente_documento_validos: ['depto_analisis_estretegico']
  entrego_solicitud: ['depto_analisis_estretegico']

solicitud_record_historial:
  nueva_solicitud: ['depto_infracciones']
  verifico_requisitos_datos_ciudadano: ['depto_infracciones']
  recepcion_esquela_identidad: ['depto_infracciones']
  aviso_requisitos_necesarios: ['depto_infracciones']
  elaboro_respuesta: ['depto_infracciones']
  respuesta_elaborada: ['depto_infracciones']
  redaccion_solicitud_datos_ciudadano: ['depto_infracciones']
  recibio_documentacion_necesaria_requisitos: ['depto_infracciones']
  envio_solicitud: ['depto_infracciones']
  solicitud_enviada: ['depto_infracciones']
  elaboro_constancia: ['depto_infracciones']
  constancia_elaborada: ['depto_infracciones']

solicitud_transporte_almacen_general_ss:
  nueva_solicitud: ['jefe_transito_evidencias']
  recepciona_indicios: ['jefe_transito_evidencias']
  verifico_requisitos: ['jefe_transito_evidencias']
  asigno_numero_oficio: ['jefe_transito_evidencias']
  transporto_indicios: ['jefe_transito_evidencias']

solicitud_antecedente_ss:
  nueva_solicitud_antecedentes: ['depto_antecedentes']
  recibio_solicitud_ciudadano: ['depto_antecedentes']
  recibio_solicitud_juez_fiscal: ['depto_antecedentes']
  recibio_solicitud_dpto_detenidos: ['depto_antecedentes']
  registro_solicitud: ['depto_antecedentes']
  verifico_solicitud: ['depto_antecedentes']
  identifico_persona: ['depto_antecedentes']
  verifica_antecedentes: ['depto_antecedentes']
  registro_solicitud: ['depto_antecedentes']
  elaboro_ficha: ['depto_antecedentes']
  envio_solicitud_orden_captura: ['depto_antecedentes']
  registro_record: ['depto_antecedentes']
  archivo_documento: ['depto_antecedentes']
  emitio_record: ['depto_antecedentes']
  entrego_record: ['depto_antecedentes']
  documento_archivado: ['depto_antecedentes']
  antecedentes_entregados: ['depto_antecedentes']

informe_urid_ss:
  nuevo_requerimiento_investigativo_fiscal: ['investigador_urid']
  toma_declaraciones: ['investigador_urid']
  nuevo_informe_pericial: ['investigador_urid']
  envio_indicios_laboratorio: ['investigador_urid']
  recepcion_resultados_laboratorio: ['investigador_urid']
  actualizo_informe_pericial: ['investigador_urid']
  registro_perfil_sospechoso: ['investigador_urid']
  genero_informe_investigativo: ['investigador_urid']
  ejecuto_orden_judicial: ['investigador_urid']
  genero_informe_final: ['investigador_urid']
  envia_informe_final_fiscal_instruccion_mp: ['investigador_urid']
  informe_final_remitido_mp: ['investigador_urid']
