dummy_workflow:
  a: ['rol1', 'rol2', 'rol3']
  b: ['worker2', 'Professor']
  c: ['rol4', 'ro6', 'rol7']

denuncia_mp:
  pendiente_evaluar: ['fiscal_mrd']
  delitos_asignados: ['fiscal_mrd']
  auto_elaborado: ['fiscal_mrd']
  fiscales_asignados: ['fiscal_coordinador_mrd']
  entregada_a_fiscalia_correspondiente: ['fiscal_mrd']
  pendiente_autorizacion_auto_cierre_administrativo: ['fiscal_coordinador_mrd']
  pendiente_recibir_notificacion_auto_cierre_firmada: ['secretaria_fiscal_mrd']
  pendiente_recibir_notificacion_de_conformidad_auto_cierre: ['secretaria_fiscal_mrd']
  auto_cierre_aceptado: ['secretaria_fiscal_mrd']
  pendiente_aceptacion_apelacion_auto_cierre: ['dgf']
  apelacion_aceptada: ['secretaria_fiscal_mrd']
  entregada_a_maadeh: ['secretaria_fiscal_mrd']
